from typing import Iterator

import numpy as np


def tau_series_generator(
    *,
    sigma: float = 1e-3,
    hurst: float = 0.5,
    tau_0: float = 0.5,
    boundary: float = 1e-3,
    n_points: int = 262144,
    seed: int = -1,
) -> Iterator[float]:
    """Generate inter-event time series (in event time space).

    Implementation of a Markovian point process:
        tau[k+1] = tau[k] + sigma^2 * (1/(2*H) - 1) *
                                          * (1/tau[k] - 1/(1-tau[k])) +
                          + sigma * epsi[k] .
    In the above tau_i is the coordinate of the point process
    (inter-event time), H is the "faked" Hurst index and epsi[k] is a
    sample of uncorrelated Gaussian noise. This process generates the
    same tau_i distribution as the fractional point process:
        tau[k+1] = tau[k] + sigma * epsi_H[k] ,
    here epsi_H[k] is a sample of fractional Gaussian noise. Both
    processes are confined to [0+boundary, 1-boundary] interval.

    Input:
        sigma: (default: 1e-3)
            Sigma parameter of the iterative equation driving the
            process. Sigma parameter controls how fast the inter-event
            time values change.
        hurst: (default: 0.5)
            Hurst index of the inter-event time series. If driving noise
            is not fractional Gaussian noise, then this is an effective
            Hurst index (the "faking" process should still generate the
            same stationary inter-event time distribution as the process
            with fGn).
        tau_0: (default: 0.5)
            Initial condition for the inter-event time series.
        boundary: (default: 1e-3)
            Fine-tunes soft boundary conditions the process is allowed
            to approach. Inter-event times are confined to interval
            [0+boundary, 1-boundary].
        n_points: (default: 262144)
            The desired length of the inter-event time series. Note that
            the length applies to the event time space (k-space) and not
            physical time space. It is advisable to use numbers which
            would be powers of 2.
        seed: (default: -1)
            RNG seed. If negative value is passed (which is the
            default), then seed will be randomly generated by
            `np.random.rand(2**20)`.

    Output:
        Generator which returns samples of inter-event time.

    Examples:
        ```
        >> from taudiff import beta_model
        >> tsg = beta_model(sigma=1e-2, hurst=0.75, n_points=16,
            seed=123)
        >> print(next(tsg))
            0.48914
        >> print(next(tsg))
            0.49911
        ```
    """
    if seed < 0:
        np.random.seed()
        seed = np.random.randint(2 ** 20)
    np.random.seed(seed)
    tau = tau_0
    drift_const = (sigma ** 2) * (1 / (2 * hurst) - 1)
    diff_const = sigma
    lb = boundary
    ub = 1 - boundary
    for _ in range(0, n_points):
        tau = (
            tau
            + drift_const * (1 / tau - 1 / (1 - tau))
            + diff_const * np.random.normal()
        )
        tau = max(min(tau, ub), lb)
        yield tau
